/* VECTOR INTRODUCTION --> A DYNAMIC ARRAY 
vector <int> name ;  ---> NAMING */


// Main Program
/*                                   #1. (high time complexity )
{
vector <int > ans;for (int i=0; i<n ;i++){
    int element = arr1[i];
    for (int j=0; j<m;j++){
        if (element == arr2[j]){
            ans.push_back(element );  // Vector me ans dalne ka tareeka 
            arr2[j]=-1;
            break;
        }
    }
}

return ans;
}*/
